# Generated by Django 3.0.7 on 2020-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is Test txext for the image will be chagned later on in Admin item'),
            preserve_default=False,
        ),
    ]
